defmodule HumanportWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :humanport

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_humanport_key",
    signing_salt: "31XV1IiX",
    same_site: "Lax"
  ]

  # OPS-03 (02-02-PLAN.md Task 1) — `:cookies` is NOT a valid `connect_info`
  # key. 02-RESEARCH.md's own Pattern 1 and this plan's action text assumed
  # it was; it is not, confirmed two ways: (1) `Phoenix.Socket.Transport
  # .load_config/1` raises `ArgumentError` at compile time for any key
  # outside `:peer_data, :trace_context_headers, :x_headers, :user_agent,
  # :sec_websocket_headers, :uri, {:session, config}` plus custom keyword
  # pairs; (2) `Phoenix.Endpoint`'s own "Connect info" moduledoc section
  # states it outright — "you can't access cookies and other headers in
  # your socket" — a deliberate cross-site-WebSocket-hijack defense, not an
  # omission. A malicious page can open a WS connection to this origin and
  # the browser will submit the visitor's cookies; if Phoenix handed those
  # to the socket unchecked, that page could ride the visitor's Access
  # session. This is why only `:session` (CSRF-token-protected) is listed
  # below.
  #
  # `HumanportWeb.Plugs.ResolveActor.call/2` snapshots the resolved actor
  # into THIS session on every successful dead-render resolve;
  # `Resolvers.CloudflareAccess`'s socket clause reads that snapshot back
  # via `get_connect_info(socket, :session)` on reconnect — see both
  # modules' moduledocs for the full mechanism and why trusting the
  # snapshot is sound (Access re-checks at the edge on every reconnect
  # regardless).
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :humanport,
    gzip: not code_reloading?,
    only: HumanportWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug AshPhoenix.Plug.CheckCodegenStatus
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :humanport
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug HumanportWeb.Router
end
