defmodule Humanport.Repo.Migrations.AddAgentKeys do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:agent_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :tenant_id, :uuid, null: false
      add :label, :text, null: false
      add :prefix, :text, null: false
      add :secret_hash, :text, null: false
      add :revoked_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:agent_keys, [:prefix], name: "agent_keys_unique_prefix_index")

    alter table(:audit_events) do
      modify :request_id, :uuid, null: true
    end

    alter table(:human_requests) do
      add :requester_agent_key_id, :uuid
    end
  end

  def down do
    alter table(:human_requests) do
      remove :requester_agent_key_id
    end

    alter table(:audit_events) do
      modify :request_id, :uuid, null: false
    end

    drop_if_exists unique_index(:agent_keys, [:prefix], name: "agent_keys_unique_prefix_index")

    drop table(:agent_keys)
  end
end
