defmodule Humanport.Repo.Migrations.AddDeadlines do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:human_requests) do
      add :deadline_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:human_requests) do
      remove :deadline_at
    end
  end
end
