defmodule Humanport.Repo.Migrations.AddChooseSupport do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:human_requests) do
      add :options, {:array, :map}
      add :allow_free_text, :boolean, null: false, default: false
      add :max_selections, :bigint, null: false, default: 1
      add :selected_option_ids, {:array, :text}
    end
  end

  def down do
    alter table(:human_requests) do
      remove :selected_option_ids
      remove :max_selections
      remove :allow_free_text
      remove :options
    end
  end
end
