defmodule Humanport.Repo.Migrations.AddContentHash do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:human_requests) do
      add :content_hash, :text
      add :decided_content_hash, :text
    end
  end

  def down do
    alter table(:human_requests) do
      remove :decided_content_hash
      remove :content_hash
    end
  end
end
