defmodule Humanport.Repo.Migrations.CreateHumanRequestsAndAuditEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:audit_events, primary_key: false) do
      add :event_id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :event_type, :text, null: false
      add :occurred_at, :utc_datetime_usec, null: false
      add :tenant_id, :uuid, null: false
      add :request_id, :uuid, null: false
      add :actor_id, :text
      add :actor_type, :text
      add :actor_label, :text
      add :actor_verified, :boolean, null: false, default: false
      add :resource_type, :text, null: false
      add :resource_id, :uuid, null: false
      add :previous_state, :text
      add :new_state, :text
      add :correlation_id, :text
      add :source_protocol, :text
      add :source_identifier, :text
      add :metadata, :map, default: %{}
    end

    execute("""
    CREATE OR REPLACE FUNCTION audit_events_append_only() RETURNS trigger AS $$
    BEGIN
      RAISE EXCEPTION 'audit_events is append-only: % is not permitted', TG_OP
        USING ERRCODE = 'integrity_constraint_violation';
    END;
    $$ LANGUAGE plpgsql;
    """)

    execute("""
    CREATE TRIGGER audit_events_no_update_delete
      BEFORE UPDATE OR DELETE ON audit_events
      FOR EACH ROW EXECUTE FUNCTION audit_events_append_only();
    """)

    execute("""
    CREATE TRIGGER audit_events_no_truncate
      BEFORE TRUNCATE ON audit_events
      FOR EACH STATEMENT EXECUTE FUNCTION audit_events_append_only();
    """)

    create table(:human_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :tenant_id, :uuid, null: false
      add :type, :text, null: false
      add :title, :text, null: false
      add :description, :text
      add :context, :map
      add :subject, :map
      add :source, :text
      add :external_correlation, :text
      add :risk, :text
      add :reversible, :text
      add :requester_label, :text
      add :requester_verified, :boolean, null: false, default: false
      add :answer, :text
      add :decision, :text
      add :decided_by, :map
      add :completed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :state, :text, null: false, default: "pending"
    end

    create index(:human_requests, [:tenant_id, :state, :inserted_at])
  end

  def down do
    drop_if_exists index(:human_requests, [:tenant_id, :state, :inserted_at])

    drop table(:human_requests)

    execute("""
    DROP TRIGGER IF EXISTS audit_events_no_truncate ON audit_events;
    """)

    execute("""
    DROP TRIGGER IF EXISTS audit_events_no_update_delete ON audit_events;
    """)

    execute("""
    DROP FUNCTION IF EXISTS audit_events_append_only();
    """)

    drop table(:audit_events)
  end
end
