defmodule Humanport.Repo.Migrations.AddAuditEventsActorMethod do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:audit_events) do
      add :actor_method, :text
    end
  end

  def down do
    alter table(:audit_events) do
      remove :actor_method
    end
  end
end
