defmodule Humanport.Repo.Migrations.AddTerminalIsFinalTrigger do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    CREATE OR REPLACE FUNCTION human_requests_terminal_is_final() RETURNS trigger AS $$
    BEGIN
      IF OLD.completed_at IS NOT NULL THEN
        RAISE EXCEPTION 'human_request % is already terminal (state=%)', OLD.id, OLD.state
          USING ERRCODE = 'integrity_constraint_violation';
      END IF;
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)

    execute("""
    CREATE TRIGGER human_requests_terminal_is_final
      BEFORE UPDATE ON human_requests
      FOR EACH ROW EXECUTE FUNCTION human_requests_terminal_is_final();
    """)
  end

  def down do
    execute("""
    DROP TRIGGER IF EXISTS human_requests_terminal_is_final ON human_requests;
    """)

    execute("""
    DROP FUNCTION IF EXISTS human_requests_terminal_is_final();
    """)
  end
end
